### ISSUE TITLE
no map widget is displied ipython 3

### ISSUE THREAD

**Issue by epifanio** [ellisonbg/ipyleaflet#9]
I installed the widget flling the readme instructions, i added the lines for off line rendering as well.
When i try to run the examples no widget is displayed. In the JS console i've this log : 

https://gist.github.com/fafd6b389d99d9252470

this the lines of code is used in the notebook : 

http://nbviewer.ipython.org/gist/epifanio/a96da4fde5c53755e562

my ipython version is (3, 1, 0, 'dev') running in Jupyter,  built before the big split.
python 3.4.3

**Comment by epifanio** [comment]
Which ipython version is supposed to work with leafletwidget widget ?

**Comment by cekees** [comment]
I've only tested  it thoroughly with  https://github.com/ellisonbg/ipython.git commit 68f6519cdfd23581ed7358fa1941ae1bbd76e5b3

**Comment by ellisonbg** [comment]
It definitely will need updating to work with ipython 3.1. @jdfreder will
know the change that need to be made...

On Thu, Apr 9, 2015 at 9:29 AM, Chris Kees <notifications@github.com> wrote:

> I've only tested it thoroughly with
> https://github.com/ellisonbg/ipython.git commit
> 68f6519cdfd23581ed7358fa1941ae1bbd76e5b3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/leafletwidget/issues/9#issuecomment-91282176>
> .
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Probably caused by https://github.com/ipython/ipython/pull/7757 .

**Comment by elyase** [comment]
Any quick fix for this?

**Comment by jdfreder** [comment]
It should be fixed in leafletwidget master now, IIRC.

**Comment by rjleveque** [comment]
I'm having trouble getting this working with IPython 3.2.0, having just updated via `conda update anaconda`.

Specifically I'm looking at `examples/DrawControl.ipynb` and changed `widget.ContainerWidget()` to `widget.Box()` based on a deprecation warning, but still nothing shows up from the `display(c)` cell.

Three cells later the `dc.last_action` cell gives the error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-07e2bef5fab6> in <module>()
----> 1 dc.last_action

AttributeError: 'DrawControl' object has no attribute 'last_action'
```

I tried the other examples an no maps show up for those either, although no exceptions are raised.

**Comment by ellisonbg** [comment]
I probably won't have time to look at this for a few weeks (travel), but am
more than willing to merge a PR that fixes any of this.

On Sat, Aug 15, 2015 at 6:49 PM, Randall J. LeVeque <
notifications@github.com> wrote:

> I'm having trouble getting this working with IPython 3.2.0, having just
> updated via conda update anaconda.
>
> Specifically I'm looking at examples/DrawControl.ipynb and changed
> widget.ContainerWidget() to widget.Box() based on a deprecation warning,
> but still nothing shows up from the display(c) cell.
>
> Three cells later the dc.last_action cell gives the error
>
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-11-07e2bef5fab6> in <module>()
> ----> 1 dc.last_action
>
> AttributeError: 'DrawControl' object has no attribute 'last_action'
>
> I tried the other examples an no maps show up for those either, although
> no exceptions are raised.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/leafletwidget/issues/9#issuecomment-131474784>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
@willingc want to have a look at this?

On Mon, Aug 17, 2015 at 9:07 AM, Brian Granger <ellisonbg@gmail.com> wrote:

> I probably won't have time to look at this for a few weeks (travel), but
> am more than willing to merge a PR that fixes any of this.
>
> On Sat, Aug 15, 2015 at 6:49 PM, Randall J. LeVeque <
> notifications@github.com> wrote:
>
>> I'm having trouble getting this working with IPython 3.2.0, having just
>> updated via conda update anaconda.
>>
>> Specifically I'm looking at examples/DrawControl.ipynb and changed
>> widget.ContainerWidget() to widget.Box() based on a deprecation warning,
>> but still nothing shows up from the display(c) cell.
>>
>> Three cells later the dc.last_action cell gives the error
>>
>> ---------------------------------------------------------------------------
>> AttributeError                            Traceback (most recent call last)
>> <ipython-input-11-07e2bef5fab6> in <module>()
>> ----> 1 dc.last_action
>>
>> AttributeError: 'DrawControl' object has no attribute 'last_action'
>>
>> I tried the other examples an no maps show up for those either, although
>> no exceptions are raised.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ellisonbg/leafletwidget/issues/9#issuecomment-131474784>
>> .
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
@ellisonbg Sure

**Comment by SylvainCorlay** [comment]
This is "fixed" now in that the master branch works with ipywidgets 5.0.0 beta

**Comment by willingc** [comment]
Thanks @SylvainCorlay. Congrats on the release too.
